apiVersion: v1
kind: Secret
metadata:
  name: cloudops-secret
  namespace: cloudops-dev
  labels:
    app.kubernetes.io/name: cloudops-secret
    app.kubernetes.io/part-of: cloudops-ai
    environment: dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://cloudops:cloudops_dev_pass@postgres.cloudops-dev.svc.cluster.local:5432/cloudops_db"
  REDIS_URL: "redis://redis.cloudops-dev.svc.cluster.local:6379/0"
