apiVersion: v1
kind: Service
metadata:
  name: cloudops-api
  namespace: cloudops-dev
  labels:
    app.kubernetes.io/name: cloudops-api
    app.kubernetes.io/part-of: cloudops-ai
    app.kubernetes.io/component: api
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: cloudops-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
