apiVersion: v1
kind: Service
metadata:
  name: cloudops-ml
  namespace: cloudops-dev
  labels:
    app.kubernetes.io/name: cloudops-ml
    app.kubernetes.io/part-of: cloudops-ai
    app.kubernetes.io/component: ml
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: cloudops-ml
  ports:
    - name: internal
      port: 8001
      targetPort: 8001
      protocol: TCP
