{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cloudops-ai.fullname" . }}-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cloudops-ai.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "cloudops-ai.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
