{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloudops-ai.fullname" . }}-postgres-data
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cloudops-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.postgres.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
{{- end }}