{{- if and .Values.eventProcessor.enabled .Values.eventProcessor.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.eventProcessor.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cloudops-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: event-processor
{{- end }}